version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/move_files
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3000
      runas: root
