version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm ci --only=production
    build:
        commands:
            - npm run build

artifacts:
  files:
    - build/**/*
    - scripts/**
    - appspec.yml