version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    volumes:
      - ./scripts:/docker-entrypoint-initaws.d